name: Build & Package All Platforms - wip

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.target_os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target_os: linux
            arch: x86_64
            runner: ubuntu-latest
          - target_os: macos
            arch: x86_64
            runner: macos-latest
          - target_os: macos
            arch: arm64
            runner: macos-latest
          - target_os: windows
            arch: x86_64
            runner: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install build dependencies (Linux)
        if: matrix.target_os == 'linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config libdbus-1-dev protobuf-compiler libprotobuf-dev

      - name: Set up Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install scons (Linux/macOS)
        if: matrix.target_os != 'windows'
        run: pip install scons

      - name: Build both (release & debug)
        run: |
          set -e
          PLATFORM_ARG=""
          ARCH_ARG=""
          if [ "${{ matrix.target_os }}" = "macos" ]; then
            PLATFORM_ARG="platform=macos"
            if [ "${{ matrix.arch }}" = "arm64" ]; then
              ARCH_ARG="arch=arm64"
              export CARGO_BUILD_TARGET=aarch64-apple-darwin
            else
              ARCH_ARG="arch=x86_64"
              export CARGO_BUILD_TARGET=x86_64-apple-darwin
            fi
          elif [ "${{ matrix.target_os }}" = "linux" ]; then
            PLATFORM_ARG="platform=linux"
            ARCH_ARG="arch=x86_64"
            export CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu
          elif [ "${{ matrix.target_os }}" = "windows" ]; then
            PLATFORM_ARG="platform=windows"
            ARCH_ARG="arch=x86_64"
            export CARGO_BUILD_TARGET=x86_64-pc-windows-msvc
          fi

          mkdir -p demo/bin

          # Debug
          scons $PLATFORM_ARG $ARCH_ARG target=template_debug -j2
          cp godot-dojo.gdextension demo/bin/godot-dojo.${{ matrix.target_os }}.${{ matrix.arch }}.debug.gdextension
          if [ "${{ matrix.target_os }}" = "windows" ]; then
            cp bin/dojo_c.dll demo/bin/dojo_c.${{ matrix.target_os }}.${{ matrix.arch }}.debug.dll || true
            cp bin/godot-dojo.dll demo/bin/godot-dojo.${{ matrix.target_os }}.${{ matrix.arch }}.debug.dll || true
            cp bin/godot-dojo.pdb demo/bin/godot-dojo.${{ matrix.target_os }}.${{ matrix.arch }}.debug.pdb || true
          elif [ "${{ matrix.target_os }}" = "linux" ]; then
            cp bin/libgodot-dojo.so demo/bin/libgodot-dojo.${{ matrix.target_os }}.${{ matrix.arch }}.debug.so || true
          elif [ "${{ matrix.target_os }}" = "macos" ]; then
            cp bin/libgodot-dojo.dylib demo/bin/libgodot-dojo.${{ matrix.target_os }}.${{ matrix.arch }}.debug.dylib || true
          fi

          # Release
          scons $PLATFORM_ARG $ARCH_ARG target=template_release -j2
          cp godot-dojo.gdextension demo/bin/godot-dojo.${{ matrix.target_os }}.${{ matrix.arch }}.release.gdextension
          if [ "${{ matrix.target_os }}" = "windows" ]; then
            cp bin/dojo_c.dll demo/bin/dojo_c.${{ matrix.target_os }}.${{ matrix.arch }}.release.dll || true
            cp bin/godot-dojo.dll demo/bin/godot-dojo.${{ matrix.target_os }}.${{ matrix.arch }}.release.dll || true
            cp bin/godot-dojo.pdb demo/bin/godot-dojo.${{ matrix.target_os }}.${{ matrix.arch }}.release.pdb || true
          elif [ "${{ matrix.target_os }}" = "linux" ]; then
            cp bin/libgodot-dojo.so demo/bin/libgodot-dojo.${{ matrix.target_os }}.${{ matrix.arch }}.release.so || true
          elif [ "${{ matrix.target_os }}" = "macos" ]; then
            cp bin/libgodot-dojo.dylib demo/bin/libgodot-dojo.${{ matrix.target_os }}.${{ matrix.arch }}.release.dylib || true
          fi

      - name: Upload binarios de este target
        uses: actions/upload-artifact@v4
        with:
          name: bin-${{ matrix.target_os }}-${{ matrix.arch }}
          path: demo/bin/*
          if-no-files-found: error

  package:
    name: Unir todos los binarios y crear zip único
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Descargar todos los binarios de los jobs
        uses: actions/download-artifact@v4
        with:
          path: all_bins

      - name: Preparar carpeta para los binarios
        run: |
          mkdir -p godot-dojo-bin
          find all_bins -type f -exec cp {} godot-dojo-bin/ \;

      - name: Empaquetar en zip único
        run: |
          TAGNAME=${GITHUB_REF##*/}
          ZIP_FILE=godot-dojo-${TAGNAME}.zip
          cd godot-dojo-bin
          zip -r "../$ZIP_FILE" .

      - name: Crear release y subir asset
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          files: godot-dojo-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
