name: Build All Platforms

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0) - leave empty to use current commit'
        required: false
        default: ''
      create_release:
        description: 'Create GitHub release'
        required: false
        default: true
        type: boolean

env:
  CARGO_TERM_COLOR: always

jobs:
  # Job 1: Build Linux
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    # Cache Rust dependencies
    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo build
      uses: actions/cache@v3
      with:
        path: |
          external/dojo.c/target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('external/dojo.c/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-

    # Cache SCons build
    - name: Cache SCons build
      uses: actions/cache@v3
      with:
        path: |
          .scons_cache
          external/godot-cpp/.scons_cache
        key: ${{ runner.os }}-scons-${{ hashFiles('SConstruct', 'external/godot-cpp/SConstruct') }}
        restore-keys: |
          ${{ runner.os }}-scons-

    # Cache system packages
    - name: Cache APT packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: build-essential pkg-config libdbus-1-dev protobuf-compiler libprotobuf-dev
        version: 1.0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install SCons
      run: pip install scons

    - name: Install Rust targets for Linux
      run: |
        rustup target add x86_64-unknown-linux-gnu

    - name: Build Linux (debug + release, x64 only)
      run: make linux-all

    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-builds
        path: demo/bin/
        retention-days: 1

  # Job 2: Build Windows (using MSVC)
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    # Cache Rust dependencies (Windows)
    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo build
      uses: actions/cache@v3
      with:
        path: |
          external/dojo.c/target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('external/dojo.c/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-

    # Cache SCons build (Windows)
    - name: Cache SCons build
      uses: actions/cache@v3
      with:
        path: |
          .scons_cache
          external/godot-cpp/.scons_cache
        key: ${{ runner.os }}-scons-${{ hashFiles('SConstruct', 'external/godot-cpp/SConstruct') }}
        restore-keys: |
          ${{ runner.os }}-scons-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install SCons
      run: pip install scons

    - name: Install Rust targets for Windows
      run: |
        rustup target add x86_64-pc-windows-msvc

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Build Windows (debug + release, x64 with MSVC)
      run: make windows-all

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-builds
        path: demo/bin/
        retention-days: 1

  # Job 3: Build macOS
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    # Cache Rust dependencies (macOS)
    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo build
      uses: actions/cache@v3
      with:
        path: |
          external/dojo.c/target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('external/dojo.c/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-

    # Cache SCons build (macOS)
    - name: Cache SCons build
      uses: actions/cache@v3
      with:
        path: |
          .scons_cache
          external/godot-cpp/.scons_cache
        key: ${{ runner.os }}-scons-${{ hashFiles('SConstruct', 'external/godot-cpp/SConstruct') }}
        restore-keys: |
          ${{ runner.os }}-scons-

    # Cache Homebrew packages
    - name: Cache Homebrew packages
      uses: actions/cache@v3
      with:
        path: |
          ~/Library/Caches/Homebrew
          /usr/local/Homebrew
        key: ${{ runner.os }}-homebrew-${{ hashFiles('.github/Brewfile') }}
        restore-keys: |
          ${{ runner.os }}-homebrew-

    - name: Install macOS dependencies
      run: |
        brew install pkg-config scons

    - name: Install Rust targets for macOS
      run: |
        rustup target add x86_64-apple-darwin
        rustup target add aarch64-apple-darwin

    - name: Build macOS (debug + release, x64 + arm64)
      run: make macos-all

    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v3
      with:
        name: macos-builds
        path: demo/bin/
        retention-days: 1

  # Job 4: Create release ZIP
  create-release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Determine version
      id: get_version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "tag=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
            echo "is_manual=true" >> $GITHUB_OUTPUT
          else
            echo "tag=manual-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
            echo "version=manual-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
            echo "is_manual=true" >> $GITHUB_OUTPUT
          fi
        else
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          echo "is_manual=false" >> $GITHUB_OUTPUT
        fi

    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts/

    - name: Collect all binaries and extension file
      run: |
        mkdir -p release
        
        # Copy all binary files (.so, .dll, .dylib)
        find artifacts/ -type f -name "*.so" -exec cp {} release/ \;
        find artifacts/ -type f -name "*.dll" -exec cp {} release/ \;
        find artifacts/ -type f -name "*.dylib" -exec cp {} release/ \;
        
        # Copy the .gdextension file
        cp godot-dojo.gdextension release/
        
        # Show what files we have
        echo "## 📁 Files found:" >> $GITHUB_STEP_SUMMARY
        ls -la release/ >> $GITHUB_STEP_SUMMARY

    - name: Create release ZIP
      run: |
        cd release
        zip -r ../godot-dojo-${{ steps.get_version.outputs.version }}.zip .

    - name: Generate release notes
      run: |
        cat > release_notes.md << EOF
        # 🚀 Godot Dojo ${{ steps.get_version.outputs.version }}
        
        ## 📦 Download:
        
        **godot-dojo-${{ steps.get_version.outputs.version }}.zip**
        - Contains binaries for all platforms
        - Includes debug and release versions
        - Includes godot-dojo.gdextension configuration file
        - Includes dojo_c.dll for Windows
        - Ready to use in any Godot project
        
        ## 🎯 Platforms included:
        
        - 🐧 **Linux**: x86_64 only
        - 🪟 **Windows**: x86_64 (compiled with MSVC, includes dojo_c.dll)
        - 🍎 **macOS**: Intel (x86_64), Apple Silicon (ARM64)
        
        ## 🚀 Quick installation:
        
        1. Download the ZIP file
        2. Extract all files
        3. Copy files to \`addons/godot-dojo/\` in your project
        4. Enable the plugin in Godot project settings
        
        Godot will automatically choose the correct binary for your system!
        
        ## ℹ️ Build information:
        - **Commit**: \`${{ github.sha }}\`
        - **Tag**: \`${{ steps.get_version.outputs.tag }}\`
        - **Date**: \`$(date -u +"%Y-%m-%d %H:%M:%S UTC")\`
        - **Trigger**: \`${{ github.event_name }}\`
        - **Windows Compiler**: MSVC (Visual Studio Build Tools)
        EOF

    - name: Upload ZIP as artifact (always)
      uses: actions/upload-artifact@v3
      with:
        name: godot-dojo-release
        path: godot-dojo-${{ steps.get_version.outputs.version }}.zip
        retention-days: 30

    - name: Create GitHub Release
      if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.create_release == 'true')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.tag }}
        name: 🚀 Godot Dojo ${{ steps.get_version.outputs.version }}
        body_path: release_notes.md
        draft: false
        prerelease: ${{ contains(steps.get_version.outputs.tag, 'alpha') || contains(steps.get_version.outputs.tag, 'beta') || contains(steps.get_version.outputs.tag, 'rc') || steps.get_version.outputs.is_manual == 'true' }}
        files: |
          godot-dojo-${{ steps.get_version.outputs.version }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Show final result
      run: |
        echo "## ✅ Build completed successfully!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**File:** godot-dojo-${{ steps.get_version.outputs.version }}.zip" >> $GITHUB_STEP_SUMMARY
        echo "**Size:** $(ls -lh godot-dojo-${{ steps.get_version.outputs.version }}.zip | awk '{print $5}')" >> $GITHUB_STEP_SUMMARY
        echo "**Trigger:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ github.event.inputs.create_release }}" = "false" ]; then
          echo "**Note:** Release creation was disabled. ZIP file uploaded as artifact only." >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📁 Files included:" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        unzip -l godot-dojo-${{ steps.get_version.outputs.version }}.zip >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY